name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install pipenv dependencies
      run: |
        pipenv install --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run python src/lint.py --threshold 6 $(find . -name '*.py')